### ISSUE TITLE
2.0.1 has made the module ESM only when it wasn't in 2.0.0

### ISSUE THREAD

**Issue by meganwalker-ibm** [chaijs/get-func-name#42] opened 2023-09-26 09:17 UTC
Trying to use chai in an CJS world now results in

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/app/node_modules/get-func-name/index.js from /path/to/app/node_modules/chai/lib/chai/utils/inspect.js not supported.
```

As can be seen on npm 2.0.0 was not an ESM module.
https://www.npmjs.com/package/get-func-name/v/2.0.0?activeTab=code does not contain the ` "type": "module",` in the `package.json`. But it does for 2.0.1.

This is breaking our existing usage of chai.

**Comment by theothersideofgod** [comment] 2023-09-26 09:28
me too
export { getFuncName };
^^^^^^

SyntaxError: Unexpected token export

is any change break this on 2.0.1

**Comment by ONLY-yours** [comment] 2023-09-26 09:36
the same error，my vitest was faild by this

**Comment by mvtm-dn** [comment] 2023-09-26 09:43
Confirm. Affected chai 4.3.x (tested on 4.3.0 and 4.3.8). 
Could you please unpublish theese version?

**Comment by mvtm-dn** [comment] 2023-09-26 09:47
As a temporary solution add dependency to get-func-name@2.0.0 in your package.json

**Comment by ONLY-yours** [comment] 2023-09-26 09:49
> As a temporary solution add dependency to get-func-name@2.0.0 in your package.json

i get error in vitest, doest it cause?
https://github.com/vitest-dev/vitest/issues/4182

**Comment by IdanAdar** [comment] 2023-09-26 09:58
> As a temporary solution add dependency to get-func-name@2.0.0 in your package.json

This worked for us.

**Comment by DiamondYuan** [comment] 2023-09-26 09:58
```
  "overrides": {
    "get-func-name": "2.0.0"
  },
```



this worked for me.

**Comment by tinpotnick** [comment] 2023-09-26 10:07
Me also - not a change for a minor version update.

**Comment by elvis-hp** [comment] 2023-09-26 10:08
f*ck. need to rollback the 2.0.0 version.

**Comment by mvtm-dn** [comment] 2023-09-26 10:13
Ok, looks like they updated the version to 3.0.0. But in npm still 2.0.1 which not works

**Comment by keithamus** [comment] 2023-09-26 10:14
There's a `2.0.2` release which should fix the issue.

**Comment by keithamus** [comment] 2023-09-26 10:15
Dupe of #41

**Closed by keithamus** 2023-09-26 10:15 UTC
